### PR TITLE
Load the widget via "shadow dom" to avoid global css pollution.

### PR DESCRIPTION
**Pull request by justinmoh**
Implemented:
- Load the widget via "shadow dom" to for better encapsulation, e.g. global css pollution.
- Misc. improvement, e.g. shadowRef to avoid reactive component, data type mismatches.
- Apply `zIndex` also to the chatbot toggle button.

### CODE REVIEW

**Comment by huseinzol05** [comment]
i have no idea about this sir, bringing the OP

**Comment by kamaroolkarim** [comment]
@justinmoh do you have any testing on your own? just to see if it's working as expected. screenshot or something would be helpful.

**Comment by justinmoh** [comment]
Closed as I've implemented new changes that add the robot background to the UI and it's only specific to NAIO. But the branch I requested to merge was `master` itself -- bad habit.

**Comment by huseinzol05** [comment]
ohhhhhhhhhh niceeeeeee

**Pull request closed without merging**
